apiVersion: v1
kind: Service
metadata:
  name: phpexpose
  labels:
    app: phpwebsite
spec:
  type: NodePort
  ports:
  -  port: 8082
     targetPort: 80
  selector:
    app: phpwebsite
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  labels:
    app: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php-deploy
  labels:
    app: phpwebsite
spec:
  selector:
    matchLabels:
      app: phpwebsite
  template:
    metadata:
      labels:
        app: phpwebsite
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: php-con
        ports:
        - containerPort: 80
          
        volumeMounts:
        - name: php-storage
          mountPath: /var/www/html/
      volumes:
      - name: php-storage
        persistentVolumeClaim:
          claimName: php-pv-claim
